export const SET_LOGIN = 'SET_LOGIN';
export const SET_USERID = 'SET_USERID';
export const SET_CHATID = 'SET_CHATID';
export const SET_CURRENT_MESSAGE = 'SET_CURRENT_MESSAGE';
export const CLEAR_CURRENT_MESSAGE = 'CLEAR_CURRENT_MESSAGE';
export const SET_CHAT_USER_LIST = 'SET_CHAT_USER_LIST';
export const SET_CHAT_MESSAGE = 'SET_CHAT_MESSAGE';
export const SET_CHAT_MESSAGES = 'SET_CHAT_MESSAGES';
export const SET_STREAM = 'SET_STREAM';
export const SET_RECEIVING_CALL = 'SET_RECEIVING_CALL';
export const SET_CALLER = 'SET_CALLER';
export const SET_CALLER_SIGNAL = 'SET_CALLER_SIGNAL';
export const SET_CALL_ACCEPTED = 'SET_CALL_ACCEPTED';
export const CALL_BEGIN = 'CALL_BEGIN';



